### PR TITLE
add native Lumen support

### PR DESCRIPTION
**Pull request by retnek**
Move Lumen specific configurations to the service provider class.
Related to #17

### CODE REVIEW

**Comment by cedricziel** [comment]
Would you be able to provide a travis file so this get's the automated testing it deserves?

**Comment by cedricziel** [comment]
Ping, @retnek are you able to provide a travis config for this repository?

**Comment by retnek** [comment]
@cedricziel please give me some days, I'm trying to assign time for this in a next few days.

**Comment by cedricziel** [comment]
No hurries, I'm super glad for anyone willing to contribute - thank you for your time!

**Comment by retnek** [comment]
I've added travis config file. Have a nice weekend!

**Comment by cedricziel** [comment]
Great - thank you!

**Review by cedricziel — APPROVED** [review]

**Pull request merged**
