### PR TITLE
Support Laravel 5.6

### PR DESCRIPTION
**Pull request by robclancy**

### CODE REVIEW

**Review by cedricziel — APPROVED** [review]
Seems plausible!

**Comment by robclancy** [comment]
Also this composer file is just bad. Set it to support 5.x and just leave it.

**Comment by cedricziel** [comment]
Has Laravel adopted semver?

**Comment by robclancy** [comment]
Who knows, even when making changes like this PR you aren't going to find bugs until it is done because you have no tests. So the weird composer restriction makes no sense.

Also what this does in the service provider is very unlikely to change since it is using Flysystem which does follow semver as far as I know.

**Comment by cedricziel** [comment]
Thank you, @robclancy !

**Pull request merged**
